// Auto-generated by OpenLane
module SSS(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input CLK,
  input CPU_RESETN,
  input BTNC,
  input BTNU,
  input BTNL,
  input BTNR,
  input BTND,
  input[15:0] SW,
  output LED16_B,
  output LED16_G,
  output LED16_R,
  output CA,
  output CB,
  output CC,
  output CD,
  output CE,
  output CF,
  output CG,
  output DP,
  output[7:0] AN,
  output[15:0] LED
);
endmodule
