###############################################################################
# Created by write_sdc
###############################################################################
current_design SSS
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name CLK -period 10.0000 [get_ports {CLK}]
set_clock_transition 0.1500 [get_clocks {CLK}]
set_clock_uncertainty 0.2500 CLK
set_propagated_clock [get_clocks {CLK}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {BTNC}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {BTND}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {BTNL}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {BTNR}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {BTNU}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {CPU_RESETN}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[0]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[10]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[11]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[12]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[13]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[14]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[15]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[1]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[2]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[3]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[4]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[5]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[6]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[7]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[8]}]
set_input_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {SW[9]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {AN[0]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {AN[1]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {AN[2]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {AN[3]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {AN[4]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {AN[5]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {AN[6]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {AN[7]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {CA}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {CB}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {CC}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {CD}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {CE}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {CF}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {CG}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {DP}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED16_B}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED16_G}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED16_R}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[0]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[10]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[11]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[12]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[13]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[14]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[15]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[1]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[2]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[3]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[4]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[5]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[6]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[7]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[8]}]
set_output_delay 2.0000 -clock [get_clocks {CLK}] -add_delay [get_ports {LED[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {CA}]
set_load -pin_load 0.0334 [get_ports {CB}]
set_load -pin_load 0.0334 [get_ports {CC}]
set_load -pin_load 0.0334 [get_ports {CD}]
set_load -pin_load 0.0334 [get_ports {CE}]
set_load -pin_load 0.0334 [get_ports {CF}]
set_load -pin_load 0.0334 [get_ports {CG}]
set_load -pin_load 0.0334 [get_ports {DP}]
set_load -pin_load 0.0334 [get_ports {LED16_B}]
set_load -pin_load 0.0334 [get_ports {LED16_G}]
set_load -pin_load 0.0334 [get_ports {LED16_R}]
set_load -pin_load 0.0334 [get_ports {AN[7]}]
set_load -pin_load 0.0334 [get_ports {AN[6]}]
set_load -pin_load 0.0334 [get_ports {AN[5]}]
set_load -pin_load 0.0334 [get_ports {AN[4]}]
set_load -pin_load 0.0334 [get_ports {AN[3]}]
set_load -pin_load 0.0334 [get_ports {AN[2]}]
set_load -pin_load 0.0334 [get_ports {AN[1]}]
set_load -pin_load 0.0334 [get_ports {AN[0]}]
set_load -pin_load 0.0334 [get_ports {LED[15]}]
set_load -pin_load 0.0334 [get_ports {LED[14]}]
set_load -pin_load 0.0334 [get_ports {LED[13]}]
set_load -pin_load 0.0334 [get_ports {LED[12]}]
set_load -pin_load 0.0334 [get_ports {LED[11]}]
set_load -pin_load 0.0334 [get_ports {LED[10]}]
set_load -pin_load 0.0334 [get_ports {LED[9]}]
set_load -pin_load 0.0334 [get_ports {LED[8]}]
set_load -pin_load 0.0334 [get_ports {LED[7]}]
set_load -pin_load 0.0334 [get_ports {LED[6]}]
set_load -pin_load 0.0334 [get_ports {LED[5]}]
set_load -pin_load 0.0334 [get_ports {LED[4]}]
set_load -pin_load 0.0334 [get_ports {LED[3]}]
set_load -pin_load 0.0334 [get_ports {LED[2]}]
set_load -pin_load 0.0334 [get_ports {LED[1]}]
set_load -pin_load 0.0334 [get_ports {LED[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BTNC}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BTND}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BTNL}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BTNR}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BTNU}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {CLK}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {CPU_RESETN}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SW[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
